# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr "Pilotes disponibles"

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr "avertissement : échec de l'ouverture du fichier spécial"

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr "en écriture"

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr "erreur de surveillance watchdog"

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"avertissement : échec du processus de pilotage automatique en temps réel"

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr "le serveur/client s'exécute trop _lentement_"

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr "les capteurs fonctionnent trop lentement"

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr "la séquence du pilote automatique s'exécute trop lentement"

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr "le servo tourne trop lentement"

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "Bibliothèque RTIMU non détectée, veuillez l'installer"

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr "Utilisation du fichier de paramètres"

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr "ERREUR : aucune IMU détectée"

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr ""
"ERREUR : échec de l'initialisation de l'IMU, aucune donnée inertielle "
"disponible"

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr "avertissement, échec du processus d'imu en temps réel"

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr "a rendu le processus imu en temps réel"

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr "réglage du biais initial du gyroscope"

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr "le processus imu n'a pas réussi à garder l'heure"

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr "impossible de lire l'IMU !"

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr "taux imu mis à taux"

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr "polarisation gyroscopique trop élevée, réinitialisation des capteurs"

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr "boussole hors de portée, remise à zéro"

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr "avertissement, n'a pas réussi à faire le processus d'étalonnage autre"

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"avertissement, échec du processus d'étalonnage inactif, tentative de renice"

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr "avertissement, échec du processus d'étalonnage"

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr "étalonnage chargé, démarrage"

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr "échec d'importation de l'ajustement d'étalonnage"

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr "valeurs d'accélération invalides"

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "trop-plein dans le socket udp du pypilot"

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "trop-plein dans le socket du pypilot"

#: pypilot/bufferedsocket.py:71
msgid "failed to send udp packet"
msgstr "échec de l'envoi du paquet udp"

#: pypilot/bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "échec de l'envoi du socket pypilot à"

#: pypilot/bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "l'envoi du socket a pris trop de temps !?!?"

#: pypilot/bufferedsocket.py:100
msgid "socket send error"
msgstr "erreur d'envoi de socket"

#: pypilot/bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "exception de socket pypilot"

#: pypilot/bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "revenir au socket non bloquant python, consommera plus de processeur"

#: pypilot/bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "erreur d'envoi de socket dans le cache du serveur"

#: pypilot/bufferedsocket.py:149
msgid "error receiving data"
msgstr "erreur de réception des données"

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"échec du chargement de la bibliothèque scientifique, impossible d'effectuer "
"la mise à jour de l'étalonnage !"

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr "avertissement, enregistrement de la valeur existante :"

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr "échec de lecture du fichier de configuration :"

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr "échec d'écriture du fichier de configuration :"

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr "Exception d'écriture du fichier de configuration :"

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr "message invalide du serveur :"

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr "avertissement, le client pypilot a déjà une connexion"

#: pypilot/client.py:311
msgid "connect failed to"
msgstr "échec de la connexion à"

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr "n'a pas réussi à se connecter à"

#: pypilot/client.py:460
msgid "usage"
msgstr "usage"

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr "définir l'hôte ou l'adresse IP"

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr "afficher des informations sur chaque type de valeur"

#: pypilot/client.py:465
msgid "continuous watch"
msgstr "veille continue"

#: pypilot/client.py:466
msgid "show this message"
msgstr "afficher ce message"

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr "n'a pas réussi à récupérer la liste de valeurs !"

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr "délai d'attente pour la récupération"

#: pypilot/client.py:507
msgid "missing"
msgstr "manquant"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot n'a pas réussi à importer les modules requis. Avez-vous oublié "
"d'exécuter sudo python3 setup.py install ?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "gpsd connecté"

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr "gpsd n'a pas réussi à se connecter"

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr "exception connexion au gps"

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr "gpsd déconnecté"

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr "succès de gpsd PROBE"

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr "la sonde gpsd a échoué"

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr "gpsd désactivé"

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd n'a pas réussi à déterminer le débit en bauds de l'appareil"

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr "délai d'attente gpsd dépassé par manque de données"

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr "gpsd a reçu un message invalide"

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr "gpsd a obtenu un indicateur pour le canal :"

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr "sonde série gpsd"

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr "nmea n'a pas réussi à analyser le gps"

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr "nmea n'a pas réussi à analyser le vent"

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr "analyse des exceptions apb"

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr "chaîne de caractères nmea non gérée"

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr "série perdue"

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr "nmea a obtenu un indicateur pour le canal de processus :"

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr "un autre processus y accède-t-il ?"

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr "le périphérique série a expiré"

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr "échec de l'ouverture"

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr "serveur nmea sur le port"

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr "la liaison a échoué."

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr "écoute sur le port"

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr "pour les connexions nmea"

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr "le serveur nmea a trop de connexions"

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr "Le client nmea a perdu la connexion"

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr "le sock nmea pas dans sockets !"

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr "nmea n'a pas réussi à désinscrire le socket"

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr "nmea n'a pas réussi à supprimer fd"

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr "nmea n'a pas réussi à supprimer l'adresse"

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr "valeur invalide"

#: pypilot/nmea.py:639
msgid "connect error"
msgstr "erreur de connexion"

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr "échec de connexion"

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr "client nmea connecté"

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr "le sondage a pris trop de temps dans le processus nmea !"

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr "le pont nmea a perdu la connexion au serveur"

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr "le pont nmea a perdu le canal vers le pilote automatique"

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr "drapeau de sondage non géré du pont nmea"

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr "boucle de processus nmea trop lente :"

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "erreur canal bloqué sur recv!"

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "rcev canal non bloqué échoué !"

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr "canal plein"

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr "ne peut pas envoyer"

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "n'a pas réussi à décoder le socket de données !"

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "n'a pas réussi à encoder le socket de données !"

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr "échec d'écriture"

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"AVERTISSEMENT : la bibliothèque python ujson a échoué, l'analyse consommera "
"plus de processeur"

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr "mauvais calibrage du gouvernail"

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr "mauvais étalonnage du servo gouvernail"

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr "Échec du gain automatique du servo gouvernail"

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr "capteur trouvé"

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr "données inconnues analysées !"

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr "erreur de lecture"

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr "trouvé plus de périphériques par chemin"

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr "retrait du gps"

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr "pas de module pyudev ! analysera souvent les périphériques USB !"

#: pypilot/serialprobe.py:356
msgid "success"
msgstr "Succès"

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr "échec de l'enregistrement de l'appareil"

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr "ERREUR aucune connexion en vue"

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr "supprimer la connexion udp en double"

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr "création du répertoire de configuration :"

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr "échec du chargement"

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr "les données de sauvegarde ont également échoué"

#: pypilot/server.py:386
msgid "failed to write"
msgstr "n'a pas réussi à écrire"

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server : échec de la liaison ; serveur déjà en route ?"

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr "le magasin persistant a pris trop de temps !"

#: pypilot/server.py:521
msgid "max connections reached"
msgstr "max de connexions atteint"

#: pypilot/server.py:524
msgid "server add socket"
msgstr "le serveur a ajouter le socket"

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr "canal interne fermé, serveur sortant"

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr "socket serveur fermé depuis le cache !!"

#: pypilot/servo.py:455
msgid "servo calibration invalid"
msgstr "étalonnage servo invalide"

#: pypilot/servo.py:565
msgid "failed to open servo on:"
msgstr "échec de l'ouverture du servo sur :"

#: pypilot/servo.py:572
msgid "failed set nonblocking/exclusive"
msgstr "échec de l'ensemble non bloquant/exclusif"

#: pypilot/servo.py:603 pypilot/signalk.py:163
msgid "found"
msgstr "trouvé"

#: pypilot/servo.py:725
msgid "loading servo calibration"
msgstr "chargement de l'étalonnage du servo"

#: pypilot/servo.py:729
msgid "WARNING: using default servo calibration!!"
msgstr "ATTENTION : utilisation de l'étalonnage par défaut du servo !!"

#: pypilot/servo.py:738
msgid "probing"
msgstr "sondage"

#: pypilot/servo.py:754
msgid "arduino servo detected"
msgstr "servo arduino détecté"

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr "appareil nécessaire pour l'option"

#: pypilot/signalk.py:66
msgid "read token"
msgstr "lire le token"

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr "échec de lecture du token"

#: pypilot/signalk.py:76
msgid "failed to"
msgstr "n'a pas réussi à"

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr "détection automatique impossible"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr "essayer"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr "ou alors"

#: pypilot/signalk.py:108
msgid "service removed"
msgstr "service supprimé"

#: pypilot/signalk.py:112
msgid "server lost"
msgstr "serveur perdu"

#: pypilot/signalk.py:118
msgid "service add"
msgstr "service ajouter"

#: pypilot/signalk.py:136
msgid "server found"
msgstr "serveur trouvé"

#: pypilot/signalk.py:145
msgid "probe"
msgstr "sonde"

#: pypilot/signalk.py:149
msgid "could not"
msgstr "ne pouvait pas"

#: pypilot/signalk.py:159
msgid "failed to retrieve/parse data from"
msgstr "n'a pas réussi à récupérer/analyser les données de"

#: pypilot/signalk.py:181
msgid "see if token is ready"
msgstr "voir si le token est prêt"

#: pypilot/signalk.py:177
msgid "received token"
msgstr "token reçu"

#: pypilot/signalk.py:187
msgid "failed to store token"
msgstr "échec du stockage du token"

#: pypilot/signalk.py:191 pypilot/signalk.py:212
msgid "error requesting access"
msgstr "erreur lors de la demande d'accès"

#: pypilot/signalk.py:210
msgid "request access url"
msgstr "demander d'accès à l'url"

#: pypilot/signalk.py:219
msgid "cannot create connection:"
msgstr "impossible de créer la connexion :"

#: pypilot/signalk.py:234
msgid "bad status, rejecting token"
msgstr "mauvais status, token rejeté"

#: pypilot/signalk.py:238
msgid "connection refused"
msgstr "Connexion rejetée"

#: pypilot/signalk.py:288
msgid "connected to"
msgstr "connecté à"

#: pypilot/signalk.py:358
msgid "Exception converting signalk->pypilot"
msgstr "Exception conversion signalk->pypilot"

#: pypilot/signalk.py:372
msgid "received"
msgstr "reçu"

#: pypilot/signalk.py:418
msgid "failed to send updates"
msgstr "échec de l'envoi des mises à jour"

#: pypilot/signalk.py:432
msgid "failed to parse msg:"
msgstr "échec de l'analyse du message :"

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr "valeur initiale non valide pour la plage de propriété"

#: pypilot/values.py:179
msgid "invalid set"
msgstr "ensemble invalide"

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr "Erreur de chargement"

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr "exception dans l'étalonnage :"

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr "avertissement : message non géré"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Contrôle du pilote automatique"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "AP"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr "N/A"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "N/A"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "N/A"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "babord"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "tribord"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilote"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr "Compas"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Vent"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Vent vrai"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Centre"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Portée"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Client"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "&Étalonnage"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Fermer"

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr "Étalonnage"

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr "Le bateau est à niveau"

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr "Réinitialiser"

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr "Alignement"

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr "Cap"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr "N/A"

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr "Décalage"

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr "Coordonnées"

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr "Mer"

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr "Bateau"

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr "Portée"

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr "Tangage"

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr "Roulis"

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr "Gîte"

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr "alignement"

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr "Âge de l'étalonnage"

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr "Effacer"

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr "étalonnage verrouillé"

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr "accélération"

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr "Points Sigma"

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr "Historique locale"

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr "actuel"

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr "Points d'étalonnage"

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr "compas"

#: ui/autopilot_control_ui.py:718
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Appuyez sur chaque bouton lorsque le gouvernail est dans la bonne position "
"pour l'étalonnage."

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr "Gouvernail"

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr "Réinitialiser l'étalonnage"

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr "Le gouvernail est centré"

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr "Le gouvernail est dans la plage tribord"

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr "Echelle"

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr "Le gouvernail est dans la plage babord"

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr "Non linéarité"

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr "gamme +-"

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr "degrés"

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr "gouvernail"

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr "paramètres"

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr "échec du chargement de pywavefront :"

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr "dimensions d'affichage invalides"

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr "Avez-vous ajouté le dossier pypilot_data ?"

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr "introuvable, la texture de boussole ne peut pas être utilisée"

#: ui/client_wx.py:47
msgid "Refresh"
msgstr "Rafraîchir"

#: ui/client_wx.py:189
msgid "Connected"
msgstr "Connecté"

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr "Déconnecté"

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr "avertissement, valeur invalide spécifiée"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "Champ pypilot"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Zéro"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Echelle +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Echelle -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Décalage /\\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Décalage \\/"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Geler"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Temps"

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr "valeurs non trouvées :"

#~ msgid "failed to load pilot"
#~ msgstr "échec du chargement du pilote"

#~ msgid "in"
#~ msgstr "dans"

#~ msgid "seconds"
#~ msgstr "secondes"

#~ msgid "nmea client failed to connect to"
#~ msgstr "Le client nmea n'a pas réussi à se connecter"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "échec de la création du socket nmea en tant qu'hôte:port"

#~ msgid "terminate calibration process"
#~ msgstr "terminer le processus d'étalonnage"
